### ISSUE TITLE
Improve linting of docs

### ISSUE THREAD

**Issue by m4sterbunny** [Consensys/docs-gha#9]
Better automate review process with linting of updated files:

DevOps have already begun work supporting this next steps to test.

There's plenty items on [this PR](https://github.com/INFURA/docs/pull/274) to setup test case for.

**Comment by m4sterbunny** [comment]
NB, this relates to (but is different to) Vale initiative https://infura.atlassian.net/browse/DOC-462

**Comment by m4sterbunny** [comment]
This overlaps with ES linting: https://infura.atlassian.net/browse/DOC-467

**Comment by alexandratran** [comment]
We can try adding this to `doc.web3signer`.

**Comment by m4sterbunny** [comment]
asking @joshuafernandes

**Comment by m4sterbunny** [comment]
@joshuafernandes ask from writing team:
linting rules exclusively for code blocks within md/mdx files -- to enforce double quotes and 2-space indents. 

?possible with [eslint/markdown](https://github.com/eslint/markdown). 

@alexandratran had a go in a [previous PR](https://github.com/MetaMask/metamask-docs/pull/1335) but there were frustrating dependency issues and ended up tabling it.

**Comment by joshuafernandes** [comment]
Yes dependencies are a pain - I've moved eslint/markdown out for the moment, and moved the md lint step in a GHA https://github.com/Consensys/docs-gha/tree/main/lint-markdown and example where its used is https://github.com/Consensys/doc.web3signer/blob/gha/.github/workflows/lint.yml#L23 

The GHA uses https://github.com/DavidAnson/markdownlint-cli2 which has capacity to do custom rules https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/CustomRules.md

I dont know if specifics with spaces in code are doable, but more specifically when things are put in Tabs (eg cli args) spacing gets interesting

**Comment by alexandratran** [comment]
@joshuafernandes I don't see anything in those `markdownlint` docs that would enable linting the actual code in Markdown code blocks, whereas I believe the [`eslint/markdown`](https://github.com/eslint/markdown) plugin is designed to specifically lint JS/JSX/TS/etc code blocks in Markdown. I was able to [configure it successfully](https://github.com/MetaMask/metamask-docs/pull/1335/files#diff-9601a8f6c734c2001be34a2361f76946d19a39a709b5e8c624a2a5a0aade05f2R1-R20) in that PR, so that when you run ESlint locally, all JS, TS, and JSON code blocks in Markdown files are updated to double quotes and 2 space indents. This is an issue we run into a lot with the number of contributors we have across the doc sites, and with older code samples that haven't been updated. However, if it's too complex to add to our current linting system, we don't need to prioritize it.

**Comment by alexandratran** [comment]
Also, looking at the [Web3Signer linting test](https://github.com/Consensys/doc.web3signer/actions/runs/10805312077/job/29972625817), I think we can increase the maximum line-length to at least 200 to yield fewer errors, and account for lines with long links.

**Comment by alexandratran** [comment]
Suggestion: Disallow smart quotes (`′` and `″`) in favor of straight quotes (`'` and `"`).

**Comment by alexandratran** [comment]
The lint/vale warnings on this PR should all be ignored, and might be a little noisy for the contributor: https://github.com/Consensys/doc.teku/pull/607/files

I.e., some words are listed in the repository's `project-words.txt` file and should be ignored by vale. Also, many instances of passive voice are fine to allow – not sure if we should keep the warning for this or if it might cause excessive friction.

**Comment by m4sterbunny** [comment]
Agree -- taking all project-words into Vale is still a todo
We can remove passive voice if it's too noisy, or set the alert level lower so writers can have it in Verbose mode

**Comment by m4sterbunny** [comment]
we have link check, spell/style check, and better linting, so closing this
